services:
  - docker
language: python
dist: python:2.7
jobs:
  include:
    - stage: build docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t mlscikitlearn .
        - docker images
        - docker tag mlscikitlearn $DOCKER_USERNAME/mlscikitlearn
        - docker push $DOCKER_USERNAME/mlscikitlearn
    # - stage: Pull and test the images
    #   script: docker run --rm $DOCKER_USERNAME/mlscikitlearn cat hello.txt
    # - script: docker run --rm $DOCKER_USERNAME/mlscikitlearn cat hello.txt